# Generated by Django 4.2.6 on 2024-02-16 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfectedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_information', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Geolocalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación')),
            ],
        ),
        migrations.CreateModel(
            name='CyberAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Marca de Tiempo')),
                ('sourceIP', models.CharField(max_length=100, verbose_name='IP de Origen')),
                ('destinationIP', models.CharField(max_length=100, verbose_name='IP de Destino')),
                ('sourcePort', models.IntegerField(verbose_name='Puerto de Origen')),
                ('destinationPort', models.IntegerField(verbose_name='Puerto de Destino')),
                ('protocol', models.CharField(max_length=50, verbose_name='Protocolo')),
                ('packetLength', models.IntegerField(verbose_name='Longitud del Paquete')),
                ('packetType', models.CharField(max_length=50, verbose_name='Tipo de Paquete')),
                ('trafficType', models.CharField(max_length=50, verbose_name='Tipo de Tráfico')),
                ('actionTaken', models.CharField(max_length=50, verbose_name='Acción Tomada')),
                ('severityLevel', models.CharField(max_length=50, verbose_name='Nivel de Severidad')),
                ('networkSegment', models.CharField(max_length=50, verbose_name='Segmento de Red')),
                ('payloadData', models.TextField(blank=True, null=True, verbose_name='Datos del Payload')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.device', verbose_name='Dispositivo')),
                ('geoLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.geolocalization', verbose_name='Geolocalización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.afecteduser', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
