# Generated by Django 4.2.6 on 2024-04-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cyberattack',
            name='payloadData',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_information',
        ),
        migrations.RemoveField(
            model_name='geolocalization',
            name='location',
        ),
        migrations.AddField(
            model_name='device',
            name='operative_system',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='Sistema Operativo'),
        ),
        migrations.AddField(
            model_name='device',
            name='rest_information',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Información Restante'),
        ),
        migrations.AddField(
            model_name='device',
            name='web_browser',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='Navegador Web'),
        ),
        migrations.AddField(
            model_name='geolocalization',
            name='city',
            field=models.CharField(default=1, max_length=50, verbose_name='Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geolocalization',
            name='locality',
            field=models.CharField(default=1, max_length=50, verbose_name='Localidad'),
            preserve_default=False,
        ),
    ]
