# Generated by Django 4.2.6 on 2024-04-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cyberattack_attacktype_cyberattack_idsipsalerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberattack',
            name='alertsWarnings',
            field=models.TextField(blank=True, null=True, verbose_name='Alertas/Advertencias'),
        ),
        migrations.AlterField(
            model_name='afecteduser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de Usuario'),
        ),
        migrations.AlterField(
            model_name='cyberattack',
            name='actionTaken',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Acción Tomada'),
        ),
        migrations.AlterField(
            model_name='cyberattack',
            name='attackType',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Ataque'),
        ),
        migrations.AlterField(
            model_name='cyberattack',
            name='destinationIP',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IP de Destino'),
        ),
        migrations.AlterField(
            model_name='cyberattack',
            name='idsIpsAlerts',
            field=models.BooleanField(default=False, null=True, verbose_name='Alertas IDS/IPS'),
        ),
        migrations.AlterField(
            model_name='cyberattack',
            name='networkSegment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Segmento de Red'),
        ),
        migrations.AlterField(
            model_name='cyberattack',
            name='packetType',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Paquete'),
        ),
        migrations.AlterField(
            model_name='cyberattack',
            name='protocol',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Protocolo'),
        ),
        migrations.AlterField(
            model_name='cyberattack',
            name='severityLevel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nivel de Severidad'),
        ),
        migrations.AlterField(
            model_name='cyberattack',
            name='sourceIP',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IP de Origen'),
        ),
        migrations.AlterField(
            model_name='cyberattack',
            name='trafficType',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Tráfico'),
        ),
        migrations.AlterField(
            model_name='device',
            name='operative_system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sistema Operativo'),
        ),
        migrations.AlterField(
            model_name='device',
            name='rest_information',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Información Restante'),
        ),
        migrations.AlterField(
            model_name='device',
            name='web_browser',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Navegador Web'),
        ),
        migrations.AlterField(
            model_name='geolocalization',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='geolocalization',
            name='locality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Localidad'),
        ),
    ]
