# Generated by Django 4.2.6 on 2024-04-20 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cyberattack_alertswarnings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyberattack',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.device', verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='cyberattack',
            name='geoLocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.geolocalization', verbose_name='Geolocalización'),
        ),
        migrations.AlterField(
            model_name='cyberattack',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.afecteduser', verbose_name='Usuario'),
        ),
    ]
