# Generated by Django 4.2.6 on 2025-02-24 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cyberattack_alertswarnings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(default='active', max_length=10, verbose_name='Status')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Example',
                'verbose_name_plural': 'Examples',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='cyberattack',
            name='device',
        ),
        migrations.RemoveField(
            model_name='cyberattack',
            name='geoLocation',
        ),
        migrations.RemoveField(
            model_name='cyberattack',
            name='user',
        ),
        migrations.DeleteModel(
            name='AfectedUser',
        ),
        migrations.DeleteModel(
            name='CyberAttack',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Geolocalization',
        ),
    ]
